services:

  redis:
    image: redis:6
    container_name: redis_6_test
    ports:
      - 6379:6379

  mysql:
    container_name: mysql_8_test
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-simplepassword}
